apiVersion: v1
kind: Secret
metadata:
  name: api-keys
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pdf-to-podcast.labels" . | nindent 4 }}
type: Opaque
stringData:
  NVIDIA_API_KEY: {{ .Values.apiKeys.nvidia | quote }}
  ELEVENLABS_API_KEY: {{ .Values.apiKeys.elevenlabs | quote }}
